In [ ]:
#Question 1

In [1]:
import numpy as np

def function(arr):
    tot_sum=0 
    max=arr[len(arr) -1][0]
    min=arr[len(arr) -1][0]
    for i in arr[len(arr) -1]:
        tot_sum += i
        if i > max :
            max = i
        if i < min:
            min = i
    avg = tot_sum/5
    print(f'Average : {avg} , Maximum Element : {max} , Minimum Element : {min}')  

arr0 = np.random.randint(1,61,60)
arr0
arr1 = arr0.reshape(12,5)
arr1

array([[31, 15,  5, 16,  6],
       [11, 24, 51, 56, 19],
       [27, 23, 59, 38, 17],
       [55, 22, 28, 14,  8],
       [18, 21, 24,  8, 20],
       [11, 59,  1,  7, 23],
       [34, 30, 41, 53, 39],
       [57, 57, 22,  3, 28],
       [54, 16, 11, 49, 40],
       [54, 16,  7, 16, 26],
       [50, 47, 12,  6, 58],
       [19, 23, 31, 26,  3]])

In [5]:
function(arr1)

Average : 20.4 , Maximum Element : 31 , Minimum Element : 3


In [2]:
        #Question 2

Average : 20.4 , Maximum Element : 31 , Minimum Element : 3


In [3]:
import numpy as np
arr  = np.array( [[1,2,3] , [4,5,6] , [7,8,9]] )
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[: , ::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])